services:
  - type: web
    name: class-2-3-song-request
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /health
